---


  - name: "move the backend binaries to server"
    become: yes
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/backend
      recursive: true


  - name: "install dependencies"
    shell: npm i


  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true


  - name: "start server"
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: /home/ubuntu/backend/dist